using System.Collections.Generic;
using UnityEngine;
using static UnityEngine.EventSystems.RecordingInputModule;

namespace GeneratedRecordedTests
{
    /// <summary>
    /// This segment touch data were generated by Unity Automated QA for the recording from the Assets folder at "Recordings\FirstTest.json"
    /// You can regenerate this file from the Unity Editor Menu: Automated QA > Generate Recorded Tests
    /// </summary>
    public static class FirstTest_Steps
    {
        public static Dictionary<string, TouchData> Actions = new Dictionary<string, TouchData>();
        static FirstTest_Steps()
        {
            Actions.Add("PRESS_Button", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.press,
                timeDelta = 0.7084679f,
                position =  new Vector3(0.4846847f, 0.4991182f),
                positional = false,
                waitSignal = "",
                emitSignal = "",
                objectName = "Button",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(-0.10625f, -0.01666667f)
            });

            Actions.Add("RELEASE_Button", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.release,
                timeDelta = 0.09677285f,
                position =  new Vector3(0.4846847f, 0.4991182f),
                positional = false,
                waitSignal = "",
                emitSignal = "",
                objectName = "Button",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(-0.10625f, -0.01666667f)
            });

            Actions.Add("PRESS_Button_2", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.press,
                timeDelta = 1.052429f,
                position =  new Vector3(0.4720721f, 0.4973545f),
                positional = false,
                waitSignal = "",
                emitSignal = "",
                objectName = "Button",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(-0.19375f, -0.05f)
            });

            Actions.Add("RELEASE_Button_2", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.release,
                timeDelta = 0.1140425f,
                position =  new Vector3(0.4720721f, 0.4973545f),
                positional = false,
                waitSignal = "",
                emitSignal = "",
                objectName = "Button",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(-0.19375f, -0.05f)
            });

            Actions.Add("PRESS_Button_3", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.press,
                timeDelta = 0.7819965f,
                position =  new Vector3(0.4720721f, 0.4973545f),
                positional = false,
                waitSignal = "",
                emitSignal = "",
                objectName = "Button",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(-0.19375f, -0.05f)
            });

            Actions.Add("RELEASE_Button_3", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.release,
                timeDelta = 0.1034274f,
                position =  new Vector3(0.4720721f, 0.4973545f),
                positional = false,
                waitSignal = "",
                emitSignal = "",
                objectName = "Button",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(-0.19375f, -0.05f)
            });

        }
    }
}
