using System.Collections.Generic;
using UnityEngine;
using static UnityEngine.EventSystems.RecordingInputModule;

namespace GeneratedRecordedTests
{
    /// <summary>
    /// This segment touch data were generated by Unity Automated QA for the recording from the Assets folder at "Recordings\SimpleButtonDown.json"
    /// You can regenerate this file from the Unity Editor Menu: Automated QA > Generate Recorded Tests
    /// </summary>
    public static class SimpleButtonDown_Steps
    {
        public static Dictionary<string, TouchData> Actions = new Dictionary<string, TouchData>();
        static SimpleButtonDown_Steps()
        {
            Actions.Add("PRESS_Button", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.press,
                timeDelta = 1.915063f,
                position =  new Vector3(0.4873874f, 0.4991182f),
                positional = false,
                waitSignal = "",
                emitSignal = "",
                objectName = "Button",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(-0.0875f, -0.01666667f)
            });

            Actions.Add("RELEASE_Button", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.release,
                timeDelta = 0.1584052f,
                position =  new Vector3(0.4873874f, 0.4991182f),
                positional = false,
                waitSignal = "",
                emitSignal = "",
                objectName = "Button",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(-0.0875f, -0.01666667f)
            });

            Actions.Add("PRESS_Button_2", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.press,
                timeDelta = 0.4622138f,
                position =  new Vector3(0.5639639f, 0.5061728f),
                positional = false,
                waitSignal = "",
                emitSignal = "",
                objectName = "Button",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(0.44375f, 0.1166667f)
            });

            Actions.Add("RELEASE_Button_2", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.release,
                timeDelta = 0.1277447f,
                position =  new Vector3(0.5603604f, 0.5097002f),
                positional = false,
                waitSignal = "",
                emitSignal = "",
                objectName = "Button",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(0.41875f, 0.1833333f)
            });

            Actions.Add("PRESS_Button_3", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.press,
                timeDelta = 0.8964934f,
                position =  new Vector3(0.4414414f, 0.5097002f),
                positional = false,
                waitSignal = "",
                emitSignal = "",
                objectName = "Button",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(-0.40625f, 0.1833333f)
            });

            Actions.Add("RELEASE_Button_3", new TouchData
            {
                pointerId = -1,
                eventType = TouchData.type.release,
                timeDelta = 0.09232378f,
                position =  new Vector3(0.4414414f, 0.5097002f),
                positional = false,
                waitSignal = "",
                emitSignal = "",
                objectName = "Button",
                objectTag = "Untagged",
                objectHierarchy = "Canvas",
                objectOffset =  new Vector3(-0.40625f, 0.1833333f)
            });

        }
    }
}
