using System.Collections;
using NUnit.Framework;
using UnityEngine;
using UnityEngine.TestTools;
using Unity.CloudTesting;

namespace GeneratedRecordedTests
{
    /// <summary>
    /// These tests were generated by Unity Automated QA for the recording from the Assets folder at "\Recordings\recording-2021-07-22-T15-33-01.json".
    /// You can regenerate this file from the Unity Editor Menu: Automated QA > Generate Recorded Tests
    /// </summary>
    public class recording_2021_07_22_T15_33_01_Tests : AutomatedQATestsBase
    {
        /// Generated from recording file: "\Recordings\recording-2021-07-22-T15-33-01.json".
        [CloudTest]
        [UnityTest]
        public IEnumerator CanPlayToEnd()
        {
            yield return PerformAction(recording_2021_07_22_T15_33_01_Steps.Actions["PRESS_Button"]); // Do a "press" action on "Canvas/Button" in scene "SampleScene".
            yield return PerformAction(recording_2021_07_22_T15_33_01_Steps.Actions["RELEASE_Button"]); // Do a "release" action on "Canvas/Button" in scene "SampleScene".
            yield return PerformAction(recording_2021_07_22_T15_33_01_Steps.Actions["PRESS_Button_2"]); // Do a "press" action on "Canvas/Button" in scene "SampleScene".
            yield return PerformAction(recording_2021_07_22_T15_33_01_Steps.Actions["RELEASE_Button_2"]); // Do a "release" action on "Canvas/Button" in scene "SampleScene".
            yield return PerformAction(recording_2021_07_22_T15_33_01_Steps.Actions["PRESS_Button_3"]); // Do a "press" action on "Canvas/Button" in scene "SampleScene".
            yield return PerformAction(recording_2021_07_22_T15_33_01_Steps.Actions["RELEASE_Button_3"]); // Do a "release" action on "Canvas/Button" in scene "SampleScene".
            yield return PerformAction(EMIT_COMPLETE); // Test complete.

            Assert.Fail();
        }

        // Steps defined by recording.
        protected override void SetUpTestClass()
        {
            RegisterStep(recording_2021_07_22_T15_33_01_Steps.Actions["PRESS_Button"]);
            RegisterStep(recording_2021_07_22_T15_33_01_Steps.Actions["RELEASE_Button"]);
            RegisterStep(recording_2021_07_22_T15_33_01_Steps.Actions["PRESS_Button_2"]);
            RegisterStep(recording_2021_07_22_T15_33_01_Steps.Actions["RELEASE_Button_2"]);
            RegisterStep(recording_2021_07_22_T15_33_01_Steps.Actions["PRESS_Button_3"]);
            RegisterStep(recording_2021_07_22_T15_33_01_Steps.Actions["RELEASE_Button_3"]);
        }

        // Initialize test run data.
        protected override void SetUpTestRun()
        {
            Test.entryScene = "SampleScene";
            Test.recordedAspectRatio = new Vector2(1110f,567f);
            Test.recordedResolution = new Vector2(1920f,1080f);
        }
    }
}
